### ISSUE TITLE
Getting an error Expiry: Error connecting to backend service

### ISSUE THREAD

**Issue by Scylla2020** [rtvi-ai/rtvi-client-web#32]
Hi I'm struggling to get the sandbox test running and get an error `Expiry: Error connecting to backend service`. 

the url `console.log('url=',import.meta.env.VITE_BASE_URL);` is undefined. Where should I set this and what is the url exactly? Thanks

**Comment by andrewkellyTH** [comment]
What was your solution? I'm running into this as well.

**Comment by Scylla2020** [comment]
I had missed this part in the Readme. You just have to create a .env file in root directory and in there set the `VITE_BACKEND_URL` to the backend service. Initially it fails to connect because by default the url is null. But yeh docs could have been better.
![image](https://github.com/user-attachments/assets/909468f5-be0b-484f-9538-a91f15cfac33)
